export interface Book {
  id: string;
  title: string;
  titleAr: string;
  author: string;
  authorAr: string;
  category: string;
  language: 'Arabic' | 'English' | 'Both';
  description: string;
  descriptionAr: string;
  coverImage: string;
  fileSize: string;
  pages: number;
  format: 'PDF' | 'EPUB' | 'PDF, EPUB';
  downloadCount: number;
  featured: boolean;
  createdAt: string;
}

export const categories = [
  { id: 'tafsir', key: 'category.tafsir', icon: '📖' },
  { id: 'hadith', key: 'category.hadith', icon: '📜' },
  { id: 'fiqh', key: 'category.fiqh', icon: '⚖️' },
  { id: 'aqeedah', key: 'category.aqeedah', icon: '🕌' },
  { id: 'seerah', key: 'category.seerah', icon: '🌙' },
  { id: 'history', key: 'category.history', icon: '📚' },
  { id: 'grammar', key: 'category.grammar', icon: '✍️' },
  { id: 'education', key: 'category.education', icon: '🎓' },
];

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'Tafsir Ibn Kathir',
    titleAr: 'تفسير ابن كثير',
    author: 'Ibn Kathir',
    authorAr: 'ابن كثير',
    category: 'tafsir',
    language: 'Arabic',
    description: 'One of the most comprehensive and widely referenced Tafsir of the Quran. Ibn Kathir provides detailed explanations using Hadith, historical context, and linguistic analysis.',
    descriptionAr: 'أحد أشمل تفاسير القرآن الكريم وأكثرها مرجعية. يقدم ابن كثير شروحات مفصلة باستخدام الحديث والسياق التاريخي والتحليل اللغوي.',
    coverImage: '',
    fileSize: '45 MB',
    pages: 2400,
    format: 'PDF',
    downloadCount: 15230,
    featured: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Sahih Al-Bukhari',
    titleAr: 'صحيح البخاري',
    author: 'Imam Al-Bukhari',
    authorAr: 'الإمام البخاري',
    category: 'hadith',
    language: 'Both',
    description: 'The most authentic collection of Hadith compiled by Imam Al-Bukhari. Contains over 7,000 authenticated narrations of Prophet Muhammad (PBUH).',
    descriptionAr: 'أصح مجموعة حديث جمعها الإمام البخاري. يحتوي على أكثر من 7000 حديث موثق عن النبي محمد ﷺ.',
    coverImage: '',
    fileSize: '38 MB',
    pages: 1800,
    format: 'PDF, EPUB',
    downloadCount: 12450,
    featured: true,
    createdAt: '2024-02-10',
  },
  {
    id: '3',
    title: 'Al-Fiqh Al-Islami',
    titleAr: 'الفقه الإسلامي',
    author: 'Wahba Al-Zuhayli',
    authorAr: 'وهبة الزحيلي',
    category: 'fiqh',
    language: 'Arabic',
    description: 'A comprehensive encyclopedia of Islamic jurisprudence covering all schools of thought with evidence and comparative analysis.',
    descriptionAr: 'موسوعة شاملة في الفقه الإسلامي تغطي جميع المذاهب الفقهية بالأدلة والتحليل المقارن.',
    coverImage: '',
    fileSize: '52 MB',
    pages: 3200,
    format: 'PDF',
    downloadCount: 8900,
    featured: true,
    createdAt: '2024-03-05',
  },
  {
    id: '4',
    title: 'The Sealed Nectar',
    titleAr: 'الرحيق المختوم',
    author: 'Safi-ur-Rahman Mubarakpuri',
    authorAr: 'صفي الرحمن المباركفوري',
    category: 'seerah',
    language: 'English',
    description: 'Award-winning biography of Prophet Muhammad (PBUH). A masterful account of the life and times of the final Messenger.',
    descriptionAr: 'سيرة حائزة على جوائز للنبي محمد ﷺ. رواية بارعة لحياة وأزمان خاتم الأنبياء والمرسلين.',
    coverImage: '',
    fileSize: '12 MB',
    pages: 580,
    format: 'PDF, EPUB',
    downloadCount: 21000,
    featured: true,
    createdAt: '2024-01-20',
  },
  {
    id: '5',
    title: 'Kitab Al-Tawhid',
    titleAr: 'كتاب التوحيد',
    author: 'Muhammad ibn Abd al-Wahhab',
    authorAr: 'محمد بن عبد الوهاب',
    category: 'aqeedah',
    language: 'Both',
    description: 'A foundational text on Islamic monotheism explaining the concept of Tawhid through Quran and Sunnah.',
    descriptionAr: 'نص أساسي في التوحيد الإسلامي يشرح مفهوم التوحيد من خلال القرآن والسنة.',
    coverImage: '',
    fileSize: '8 MB',
    pages: 320,
    format: 'PDF',
    downloadCount: 9500,
    featured: false,
    createdAt: '2024-04-12',
  },
  {
    id: '6',
    title: 'Al-Ajrumiyyah',
    titleAr: 'الآجرومية',
    author: 'Ibn Ajurrum',
    authorAr: 'ابن آجروم',
    category: 'grammar',
    language: 'Arabic',
    description: 'The classic primer for Arabic grammar studies. An essential starting point for students of the Arabic language.',
    descriptionAr: 'الكتاب الكلاسيكي لدراسة النحو العربي. نقطة انطلاق أساسية لطلاب اللغة العربية.',
    coverImage: '',
    fileSize: '3 MB',
    pages: 120,
    format: 'PDF',
    downloadCount: 6700,
    featured: false,
    createdAt: '2024-05-01',
  },
  {
    id: '7',
    title: 'Stories of the Prophets',
    titleAr: 'قصص الأنبياء',
    author: 'Ibn Kathir',
    authorAr: 'ابن كثير',
    category: 'history',
    language: 'English',
    description: 'The accounts of the Prophets of Allah from Adam to Muhammad, compiled from authentic sources.',
    descriptionAr: 'قصص أنبياء الله من آدم إلى محمد ﷺ، مجمعة من مصادر موثوقة.',
    coverImage: '',
    fileSize: '15 MB',
    pages: 650,
    format: 'PDF, EPUB',
    downloadCount: 18300,
    featured: false,
    createdAt: '2024-02-28',
  },
  {
    id: '8',
    title: 'Riyad as-Salihin',
    titleAr: 'رياض الصالحين',
    author: 'Imam An-Nawawi',
    authorAr: 'الإمام النووي',
    category: 'hadith',
    language: 'Both',
    description: 'A compilation of verses from the Quran and Hadith by Imam An-Nawawi. One of the most widely read books in Islamic literature.',
    descriptionAr: 'مجموعة من آيات القرآن والأحاديث جمعها الإمام النووي. أحد أكثر الكتب قراءة في الأدب الإسلامي.',
    coverImage: '',
    fileSize: '20 MB',
    pages: 950,
    format: 'PDF',
    downloadCount: 14200,
    featured: true,
    createdAt: '2024-03-18',
  },
];
